// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts`

interface CloudflareEnv {
	STAR_VOICE_TTS_KV: KVNamespace;
	NEXTJS_ENV: string;
	SILICONFLOW_API_KEY: string;
	ASSETS: Fetcher;
}
